spring:
  application:
    name: user-api

  datasource:
    url: jdbc:mysql://localhost:3306/user
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true