spring:
  application:
    name: user-api
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  graphql:
    graphiql:
      enabled: true
      endpoint: /graphql
      mapping: /graphiql